# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: SSH Auto Deploy
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          # remote host
          HOST: ${{ secrets.RSYNC_DEPLOY_HOST }}
          # username
          USERNAME: ${{ secrets.RSYNC_DEPLOY_USER }}
          # password
          PASSWORD: ${{ secrets.RSYNC_DEPLOY_PASSWORD }}
          # port
          PORT: 22
          # local path
          SOURCE: 'dist/'
          # remote target
          TARGET: ${{ secrets.RSYNC_DEPLOY_DEST_PATH }}
          # upload success execute command
          AFTER_COMMAND: 'npm install && npm run build --if-present'

